#! /bin/sh

if test "$1" = ""; then
    echo Usage: $0 \<prog\>
    exit 1
fi

sed -i \
    "s/ \*/ ×/g;
     s/ge/x≥t/g;
     s/eq/x=t/g;
     s, /, ÷,g;
     s/x%t/x⇌t/g;
     s,x/t,x⇌t,g;
     s,ixi,|x|,g;
     s/x2/x²/g;
     s/yx/yˣ/g;
     s/sqr/√x/g;
     s/s+/∑+/g;
     s/pi/π/g;
     s,p/r,P→R,g;
     s/lbl a$/lbl A/g;
     s/lbl b$/lbl B/g;
     s/lbl c$/lbl C/g;
     s/lbl d$/lbl D/g;
     s/lbl e$/lbl E/g;
     s/lbl a'$/lbl A'/g;
     s/lbl b'$/lbl B'/g;
     s/lbl c'$/lbl C'/g;
     s/lbl d'$/lbl D'/g;
     s/lbl e'$/lbl E'/g;
     s/lbl a /lbl A /g;
     s/lbl b /lbl B /g;
     s/lbl c /lbl C /g;
     s/lbl d /lbl D /g;
     s/lbl e /lbl E /g;
     s/lbl a' /lbl A' /g;
     s/lbl b' /lbl B' /g;
     s/lbl c' /lbl C' /g;
     s/lbl d' /lbl D' /g;
     s/lbl e' /lbl E' /g;
     " $1
