#! /usr/bin/python3

import getopt
import sys
import os
import string

file = sys.argv[1]

print(file)

content = open(file, 'r').readlines()
newcontent = []

style = [ '<STYLE TYPE="text/css">',
          '.yellowbutton',
          '  {',
          '    background : #FFE071;',
          '    padding : 0.1em 0.5em 0.1em;',
          '    border : 1pt solid black;',
          '    font-weight : bold;',
          '  }',
          '',
          '.brownbutton',
          '  {',
          '    background : #53301B;',
          '    padding : 0.1em 0.5em 0.1em;',
          '    border : 1pt solid black;',
          '    font-weight : bold;',
          '    color : #ac9e80;',
          '  }',
          '',
          '.whitebutton',
          '  {',
          '    background : #E0DDC5;',
          '    padding : 0.1em 0.5em 0.1em;',
          '    border : 1pt solid black;',
          '    font-weight : bold;',
          '    color : #222424;',
          '  }',
          '',
          '.alttext',
          '  {',
          '    background : #222424;',
          '    padding : 0.1em 0.6em 0.1em;',
          '    font-weight : bold;',
          '    color : #ac9e80;',
          '  }',
          '',
          '.deflist DT',
          '  {',
          '    display : compact;',
          '    font-weight : bold;',
          '  }',
          '.deflist DD',
          '  {',
          '    margin-left : 4em;',
          '  }',
          '',
          '.display',
          ' {',
          '    color : red;',
          '    font-weight : bold;',
          '    font-family: courier bold;',
          '    text-align : right;',
          '    margin-right : 2em;',
          ' }',
          '.displayb',
          ' {',
          '    padding: 0em 0.5em 0em;',
          '    color: red;',
          '    background: #eeeeee;',
          '    font-weight: bold;',
          '    font-family: courier bold;',
          '    font-size: 1.1em;',
          ' }',
          '</STYLE>' ]

is_style=False

for c in content:
    if c.lower().find("<style") != -1:
        is_style=True
        for s in style:
            newcontent.append(s + "\n")

    if not is_style:
        newcontent.append(c);

    if c.lower().find("</style") != -1:
        is_style=False

# write new content
f = open(file, "w+");
f.writelines(newcontent)
f.close()
