#! /usr/bin/python3
#
# Change base64 encoded images from help file. The source image must be in SVG
# format. In the HTML file, just place initially:
#
#    <IMG ALT="Name Of Image"
#    ">
#
# Then call:
#
#    $ changesvg /path/to/art/directory /path/to/help/file
#
# The IMG tag above will be replaced by the base64 encoded PNG created out of
# the SVG file using inkscape. The final HTML will look like:
#
#
#    <IMG ALT="Name Of Image" src="data:image/png;base64,
#    iVBORw0KGgoAAAANSUhEUgAAAV4AAADeCAYAAAB17Gh2AAAABHNCSVQICAgIfAhkiAAAAA
#    lwSFlzAAAHsAAAB7AB1IKDYgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vu
#    ...
#    ">
#
# Note that all attributes before the ALT one are kept, others are lost.
#
# The actual SVG file to use is based in the ALT attribute content. All
# letters are converted to lower-case and spaces to '-'.
#
# To replace all images in help text from Git root repository:
#
#    $ find modules -name "help*" -exec util/changesvg $PWD/art {} \;

import getopt
import sys
import os
import string
import re
import base64
import pyexiv2

MAX_HEIGHT = 500

# width of the PNG image, the height is kept with proportion
WIDTH = 500

if len(sys.argv) != 3:
    sys.exit("usage: changesvg <art_directory> <help_file>")

art = sys.argv[1]
file = sys.argv[2]

print(file)

def set_new_width(file):
    global WIDTH
    metadata = pyexiv2.ImageMetadata(file)
    metadata.read()
    dim = metadata.dimensions
    if(dim[1] > MAX_HEIGHT):
        WIDTH *= (MAX_HEIGHT / dim[1])
    WIDTH = int(WIDTH)

content = open(file, 'r').readlines()
newcontent = []

is_img=False

for c in content:
    if c.lower().find("<img") != -1:
        alt = re.search('^(.*) ALT="([^"]*)".*$', c)
        if alt != None:
            svgfile = os.path.join(art,alt.group(2).lower() + '.svg').replace(' ', '-')


            if os.path.exists(svgfile):
                is_img = True
                os.system("inkscape --export-area-drawing --batch-process --export-width=%d --export-filename=/tmp/art.png %s" % (WIDTH, svgfile))
                set_new_width("/tmp/art.png")
                if(WIDTH != 350):
                    os.system("inkscape --export-area-drawing --batch-process --export-width=%d --export-filename=/tmp/art.png %s" % (WIDTH, svgfile))

                os.system("zopflipng -y --iterations=20 --filters=01234mep --lossy_8bit --lossy_transparent /tmp/art.png /tmp/artc.png")
                initial_data = open('/tmp/artc.png', 'rb').read()
                encoded_data = base64.b64encode(initial_data).decode('utf-8')
                newcontent.append('%s ALT="%s" WIDTH="98%%" SRC="data:image/png;base64,' % (alt.group(1), alt.group(2)) + '\n')
                for i in range((int)(len(encoded_data)/70)+1):
                    newcontent.append(encoded_data[i*70:(i+1)*70] + '\n')
            else:
                print("skip: svg file '%s' not found" % svgfile)

    if not is_img:
        newcontent.append(c);

    if is_img == True and c.lower().find('">') != -1:
        is_img=False
        newcontent.append(c);

# write new content
f = open(file, "w+");
f.writelines(newcontent)
f.close()
